let stockActual = [
    {id: 1, temporada: "Atemporal", nombre: "Remera Cartas", articulo: "Remera", descrip: "Talle S/M. Como nueva, sin detalles.", precio: 450, image: '/img/remera.jpg'},
    {id: 2, temporada: "Otonio-invierno", nombre: "Campera de Jean Negra", articulo: "Campera", descrip: "Talle 40. Detalles en el cuello.", precio: 1920, image: '/img/campera.jpg'},
    {id: 3, temporada: "Otonio-invierno",  nombre: "Cardigan Zara", articulo: "Buzo", descrip: "Talle M/L. Como nueva, sin detalles.", precio: 670, image: '/img/buzo.jpg'},
    {id: 4, temporada: "Verano", nombre: "Remera Volados Rosa", articulo: "Remera", descrip: "Talle único. Nueva con etiqueta.", precio: 400, image: '/img/remera2.jpg'},
    {id: 5, nombre: "Camison Olivo", articulo: "Remera", descrip: "Talle único. Como nuevo, unisex.", precio: 590, image: '/img/remera3.jpg'},
    {id: 6, temporada: "Atemporal", nombre: "Jean Mom Prelavado", articulo: "Pantalon", descrip: "Talle 42. Con detalles en el cierre.", precio: 1340, image: '/img/pantalon2.jpg'},
    {id: 7, temporada: "Verano",nombre: "Top Bordado", articulo: "Verano", descrip: "Talle único(chico). Sin detalles, como nueva.", precio: 380, image: '/img/verano.jpg'},
    {id: 8, temporada: "Otonio-invierno", nombre: "Cardigan Estampado", articulo: "Buzo", descrip: "Talle L. Con detalles en el cuello.", precio: 630, image: '/img/buzo2.jpg'},
    {id: 9, temporada: "Otonio-invierno", nombre: "Blazer Rojo Engomado", articulo: "Campera", descrip: "Talle M. Nueva con etiqueta", precio: 2700, image: '/img/campera2.jpg'},
    {id: 10, temporada: "Verano", nombre: "Remera Volados Blanca", articulo: "Verano", descrip: "Talle único. Nueva con etiqueta.", precio: 400, image: '/img/verano2.jpg'},
    {id: 11, temporada: "Atemporal",  nombre: "Camison American S", articulo: "Remera", descrip: "Talle L. Con detalles en el borde inferior.", precio: 590, image: '/img/remera4.jpg'},
    {id: 12, temporada: "Atemporal", nombre: "Jean H&M", articulo: "Pantalon", descrip: "Talle 36. Con detalles pequeños.", precio: 100, image: '/img/pantalon2.jpg'},
    {id: 13, temporada: "Verano", nombre: "Remera Heroine", articulo: "Remera", descrip: "Talle XS. Como nueva, sin detalles.", precio: 380, image: '/img/remera5.jpg'},
    {id: 14, temporada: "Otonio-invierno", nombre: "Buzo Negro", articulo: "Buzo", descrip: "Talle único. Hilo grueso, como nueva.", precio: 500, image: '/img/buzo4.jpg'},
    {id: 15, temporada: "Otonio-invierno", nombre: "Campera Impermeable", articulo: "Campera", descrip: "Talle M/L. Sin detalles, talle para hombre.", precio: 2130, image: '/img/campera3.jpg'},
    {id: 16, temporada: "Atemporal", nombre: "Jean Wide Leg", articulo: "Pantalon", descrip: "Talle 36. Nuevo, las roturas son de fábrica.", precio: 1700, image: '/img/pantalon3.jpg'},
    {id: 17, temporada: "Verano", nombre: "Remera Leopardo", articulo: "Remera", descrip: "Talle XS. Nueva, con etiqueta.", precio: 310, image: '/img/remera6.jpg'},
    {id: 18, temporada: "Otonio-invierno", nombre: "Campera con Cierre", articulo: "Campera", descrip: "Talle M. Como nueva, sin detalles.", precio: 520, image: '/img/campera4.jpg'},
    {id: 19, temporada: "Otonio-invierno", nombre: "Buzo Calaveras", articulo: "Buzo", descrip: "Talle L. Con detalles en hilos sueltos.", precio: 100, image: '/img/buzo5.jpg'},
    {id: 20, temporada: "Verano", nombre: "Top con Encaje", articulo: "Verano", descrip: "Talle S. Con detalles pequeños.", precio: 480, image: '/img/verano3.jpg'},
    {id: 21, temporada: "Atemporal", nombre: "Camison Harley", articulo: "Remera", descrip: "Talle único. Como nueva, sin detalles.", precio: 620, image: '/img/remera7.jpg'},
    {id: 22, temporada: "Atemporal", nombre: "Jean Wide Leg", articulo: "Pantalon", descrip: "Talle 38. Detalles en el ruedo.", precio: 1990, image: '/img/pantalon4.jpg'},
    {id: 23, temporada: "Otonio-invierno", nombre: "Pullover Rombos", articulo: "Buzo", descrip: "Talle único. Con detalles pequeños.", precio: 380, image: '/img/buzo6.jpg'},
    {id: 24, temporada: "Otonio-invierno", nombre: "Buzito Lana", articulo: "Remera", descrip: "Talle XS. Como nueva, sin detalles", precio: 510, image: '/img/remera8.jpg'},
    {id: 25, temporada: "Verano", nombre: "Pollera Cuadrillé", articulo: "Verano", descrip: "Talle S. Como nueva, sin detalles", precio: 620, image: '/img/verano4.jpg'},
    {id: 26, temporada: "Atemporal", nombre: "Campera Jean", articulo: "Campera", descrip: "Talle 44. Con detalles en el cuello.", precio: 2340, image: '/img/campera5.jpg'},
    {id: 27, temporada: "Atemporal", nombre: "Jean Butterfly", articulo: "Pantalon", descrip: "Talle 36. Sin detalles, como nuevo", precio: 1820, image: '/img/pantalon5.jpg'},
    {id: 28, temporada: "Otonio-invierno", nombre: "Buzo Mangas Globo", articulo: "Buzo", descrip: "Talle único. Como nueva, sin detalles", precio: 710, image: '/img/buzo7.jpg'},
    {id: 29, temporada: "Verano", nombre: "Short Rosa", articulo: "Verano", descrip: "Talle 36. Sin detalles, incluye el cinto.", precio: 800, image: '/img/verano5.jpg'},
    {id: 30, temporada: "Atemporal", nombre: "Camisa Manchas", articulo: "Remera", descrip: "Talle M. Estampada, con detalles en el cuello.", precio: 0, image: '/img/remera9.jpg'},
    {id: 31, temporada: "Atemporal", nombre: "Camison Emoji", articulo: "Remera", descrip: "Talle único. Con detalles pequeños", precio: 510, image: '/img/remera10.jpg'},
    {id: 32, temporada: "Otonio-invierno", nombre: "Buzo Rayado", articulo: "Buzo", descrip: "Talle único. Sin detalles, como nueva", precio: 490, image: '/img/buzo8.jpg'},
    {id: 33, temporada: "Otonio-invierno", nombre: "Buzo Corazones", articulo: "Buzo", descrip: "Talle S. Con detalles en las mangas.", precio: 670, image: '/img/buzo9.jpg'},
    {id: 34, temporada: "Atemporal", nombre: "Remera Ramones", articulo: "Remera", descrip: "Talle M. Como nueva, sin detalles.", precio: 510, image: '/img/remera11.jpg'},
    {id: 35, temporada: "Atemporal", nombre: "Jean con Parches", articulo: "Pantalon", descrip: "Talle 40. Como nuevo, sin detalles.", precio: 1630, image: '/img/pantalon7.jpg'},
    {id: 36, temporada: "Atemporal", nombre: "Remera Evil", articulo: "Remera", descrip: "Talle único. Con detalles pequeños.", precio: 480, image: '/img/remera12.jpg'},
    {id: 37, temporada: "Otonio-invierno", nombre: "Buzo Rayado B&N", articulo: "Buzo", descrip: "Talle XS. Con detalle en los hilos.", precio: 570, image: '/img/buzo10.jpg'},
    {id: 38, temporada: "Otonio-invierno", nombre: "Chomba Lana", articulo: "Remera", descrip: "Talle S. Sin detalles, como nueva.", precio: 450, image: '/img/remera13.jpg'},
    {id: 39, temporada: "Atemporal", nombre: "Pantalon Sastre", articulo: "Pantalon", descrip: "Talle 42. Con detalles en el ruedo.", precio: 1580, image: '/img/pantalon8.jpg'},
    {id: 40, temporada: "Otonio-invierno", nombre: "Buzo Lana", articulo: "Buzo", descrip: "Talle único. Nueva con etiqueta.", precio: 600, image: '/img/buzo11.jpg'},
    {id: 41, temporada: "Otonio-invierno", nombre: "Campera The North Face", articulo: "Campera", descrip: "Talle L. Como nueva, sin detalles.", precio: 2400, image: '/img/campera8.jpg'},
    {id: 42, temporada: "Verano", nombre: "Conjunto Top", articulo: "Remera", descrip: "Talle único. Como nuevas, vienen ambas.", precio: 610, image: '/img/remera14.jpg'},
    {id: 43, temporada: "Verano", nombre: "Pollera Jean", articulo: "Verano", descrip: "Talle 36. Sin detalles, como nuevas.", precio: 100, image: '/img/verano7.jpg'},
    {id: 44, temporada: "Otonio-invierno", nombre: "Campera Amarilla", articulo: "Campera", descrip: "Talle M. Como nueva, detalles muy pequeños.", precio: 2100, image: '/img/campera9.jpg'},
    {id: 45, temporada: "Verano", nombre: "Remera Angels", articulo: "Remera", descrip: "Talle único. Con detalles en la costura inferior.", precio: 490, image: '/img/remera16.jpg'},
    {id: 46, temporada: "Atemporal", nombre: "Jean Simonette", articulo: "Pantalon", descrip: "Talle 44. Detalles en el ruedo.", precio: 1930, image: '/img/pantalon9.jpg'},
    {id: 47, temporada: "Atemporal", nombre: "Jean Claro", articulo: "Pantalon", descrip: "Talle 42. Detalles en la rodilla.", precio: 1780, image: '/img/pantalon10.jpg'},
    {id: 48, temporada: "Atemporal", nombre: "Básica Olivo", articulo: "Remera", descrip: "Talle único. Nueva con etiqueta.", precio: 600, image: '/img/remera17.jpg'},
    {id: 49, temporada: "Otonio-invierno", nombre: "Buzo Cuello Tortuga", articulo: "Buzo", descrip: "Talle único. Sin detalles, como nueva.", precio: 650, image: '/img/buzo12.jpg'},
    {id: 50, temporada: "Verano", nombre: "Camisa Floreada", articulo: "Verano", descrip: "Talle M. Nueva con etiqueta.", precio: 510, image: '/img/verano8.jpg'},
    {id: 51, temporada: "Verano", nombre: "Short Gamuza", articulo: "Pantalon", descrip: "Talle 40. Con detalles pequeños.", precio: 650, image: '/img/verano9.jpg'},
    {id: 52, temporada: "Verano", nombre: "Short Engomado", articulo: "Pantalon", descrip: "Talle 36. Como nuevo, sin detalles.", precio: 1200, image: '/img/short_engomado.jpg'},
  
  ]